FROM nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /app
RUN apt-get update && \
    apt-get install -y -qq ffmpeg aria2 python3-pip &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY requirements-runpod.txt .
RUN pip install --no-cache-dir -r requirements-runpod.txt
