FROM ryurchik/rvc-runtime:v1
WORKDIR /app
COPY . .
RUN tools/dlmodels_runpod.sh
ENV BUCKET=bucket
ENV AWS_ACCESS_KEY_ID=key
ENV AWS_SECRET_ACCESS_KEY=secret
RUN python3 tools/download_data_from_s3.py
CMD [ "python3", "-u", "/app/runpod_api_handler.py" ]
