name: pull format

on: [pull_request]

permissions:
  contents: write

jobs:
  pull_format:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
      fail-fast: false

    continue-on-error: true

    steps:
      - name: checkout
        continue-on-error: true
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Black
        run: pip install "black[jupyter]"

      - name: Run Black
        # run: black $(git ls-files '*.py')
        run: black .

      - name: Commit Back
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Code Formatter Change
