name: Unit Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
      fail-fast: true

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt -y install ffmpeg
        sudo apt -y install -qq aria2
    - name: Download models
      run: |
        aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/hubert_base.pt -d ./ -o hubert_base.pt
    - name: Install dependencies
      run: uv sync
    - name: Test step 1 & 2
      run: |
        mkdir -p logs/mi-test
        touch logs/mi-test/preprocess.log
        uv run python infer/modules/train/preprocess.py logs/mute/0_gt_wavs 48000 8 logs/mi-test True 3.7
        touch logs/mi-test/extract_f0_feature.log
        uv run python infer/modules/train/extract/extract_f0_print.py logs/mi-test $(nproc) pm
        uv run python infer/modules/train/extract_feature_print.py cpu 1 0 0 logs/mi-test v1 True
